# Generated by Django 5.2 on 2025-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_trip_tripphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
