# Generated by Django 5.2 on 2025-05-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_trip_latitude_trip_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
