# Generated by Django 5.2 on 2025-05-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_trip_latitude_alter_trip_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
