# Generated by Django 5.2 on 2025-05-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_customuser_is_public_customuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='tripphoto',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='tripphoto',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='User.trip'),
        ),
    ]
