# Generated by Django 5.2 on 2025-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_tripphoto_image_tripphoto_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripphoto',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tripphoto',
            name='image',
            field=models.ImageField(default=None, upload_to='trip_photos/'),
        ),
    ]
