# Generated by Django 5.2 on 2025-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_tripphoto_image_url_tripphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripphoto',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
