# Generated by Django 5.2 on 2025-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_tripphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripphoto',
            name='image',
            field=models.URLField(),
        ),
    ]
