# Generated by Django 5.2 on 2025-05-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_tripphoto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripphoto',
            old_name='image',
            new_name='image_url',
        ),
    ]
